# DevPocket Server Test Environment Docker Compose
# Minimal setup for running integration tests

version: '3.8'

services:
  # PostgreSQL Test Database
  postgres-test:
    image: postgres:15-alpine
    container_name: devpocket-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: devpocket_test
      POSTGRES_USER: devpocket
      POSTGRES_PASSWORD: devpocket_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql:ro
    networks:
      - devpocket-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devpocket -d devpocket_test"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: ["postgres", "-c", "log_statement=none", "-c", "log_duration=off", "-c", "log_min_duration_statement=-1"]

  # Redis for test caching (optional, lightweight)
  redis-test:
    image: redis:7-alpine
    container_name: devpocket-redis-test
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - devpocket-test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_test_data:
    driver: local

networks:
  devpocket-test-network:
    driver: bridge