# DevPocket Secrets Template
# Copy this file to secrets.yaml and replace placeholder values
# DO NOT commit secrets.yaml to version control

apiVersion: v1
kind: Secret
metadata:
  name: devpocket-secrets
  namespace: default
  labels:
    app.kubernetes.io/name: devpocket
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: devpocket-platform
type: Opaque
stringData:
  # Database connection
  database-url: "postgresql://username:password@postgres-host:5432/devpocket_server"
  
  # Redis connection
  redis-url: "redis://redis-host:6379"
  
  # JWT secrets (generate strong random values)
  jwt-secret: "REPLACE_WITH_STRONG_JWT_SECRET"
  jwt-refresh-secret: "REPLACE_WITH_STRONG_JWT_REFRESH_SECRET"
  
  # Google OAuth (optional)
  google-client-id: "your-google-client-id"
  google-client-secret: "your-google-client-secret"
  
  # Email service (optional)
  resend-api-key: "your-resend-api-key"

---
# Example of how to create secrets from command line:
# kubectl create secret generic devpocket-secrets \
#   --from-literal=database-url="postgresql://user:pass@host:5432/db" \
#   --from-literal=redis-url="redis://host:6379" \
#   --from-literal=jwt-secret="your-jwt-secret" \
#   --from-literal=jwt-refresh-secret="your-refresh-secret" \
#   --from-literal=google-client-id="your-google-client-id" \
#   --from-literal=google-client-secret="your-google-client-secret" \
#   --from-literal=resend-api-key="your-resend-api-key"