apiVersion: v1
kind: Namespace
metadata:
  name: {{ NAMESPACE }}
  labels:
    app.kubernetes.io/name: devpocket
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: devpocket-platform
    environment: {{ ENVIRONMENT }}
  annotations:
    description: "DevPocket {{ ENVIRONMENT }} environment namespace"