apiVersion: v1
kind: Service
metadata:
  name: devpocket-nodejs
  namespace: {{ NAMESPACE }}
  labels:
    app.kubernetes.io/name: devpocket-nodejs
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: devpocket-platform
    app.kubernetes.io/version: "{{ VERSION }}"
    app.kubernetes.io/environment: {{ ENVIRONMENT }}
  annotations:
    description: "DevPocket API server service for {{ ENVIRONMENT }} environment"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: devpocket-nodejs
    app.kubernetes.io/component: api-server