apiVersion: v1
kind: Service
metadata:
  name: devpocket-nodejs
  namespace: {{ NAMESPACE }}
  labels:
    app.kubernetes.io/name: devpocket-nodejs
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: devpocket-platform
    environment: {{ ENVIRONMENT }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: devpocket-nodejs
    app.kubernetes.io/component: api-server