name: Deploy to Development

on:
  push:
    branches: [dev/*]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy even if tests fail'
        required: false
        default: false
        type: boolean

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: digitop/devpocket-nodejs
  KUBERNETES_NAMESPACE: devpocket-dev
  DOMAIN: api.dev.devpocket.app

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Run linting
        run: pnpm lint

      - name: Check formatting
        run: pnpm format --check

      - name: Run type checking
        run: pnpm build

      - name: Run tests
        run: pnpm test:ci:coverage
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-for-ci
          GOOGLE_CLIENT_ID: fake-google-client-id
          GOOGLE_CLIENT_SECRET: fake-google-client-secret
          RESEND_API_KEY: fake-resend-api-key

  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    needs: test
    if: success() || github.event.inputs.force_deploy == 'true'
    
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
      build-number: ${{ github.run_number }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract branch name
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_SAFE=${BRANCH_NAME//\//-}
          echo "BRANCH_SAFE=${BRANCH_SAFE}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=dev-latest
            type=raw,value=dev-${{ env.BRANCH_SAFE }}-${{ github.run_number }}-${{ env.SHORT_SHA }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Image digest
        run: echo "Built image with digest ${{ steps.build.outputs.digest }}"

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Kubernetes Development
    needs: [test, build-and-push]
    if: success() || github.event.inputs.force_deploy == 'true'
    environment: development
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DEV }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get namespaces

      - name: Create namespace if not exists
        run: |
          kubectl create namespace ${{ env.KUBERNETES_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Prepare environment-specific manifests
        run: |
          # Create dev-specific manifests from templates
          mkdir -p k8s/dev
          
          # Copy and modify deployment for dev environment
          sed -e "s/namespace: devpocket-prod/namespace: ${{ env.KUBERNETES_NAMESPACE }}/g" \
              -e "s/image: docker.io\/digitop\/devpocket-nodejs:latest/image: ${{ env.DOCKER_REGISTRY }}\/${{ env.DOCKER_IMAGE }}:dev-${{ env.BRANCH_SAFE }}-${{ github.run_number }}-${{ env.SHORT_SHA }}/g" \
              -e "s/value: \"production\"/value: \"development\"/g" \
              -e "s/value: \"info\"/value: \"debug\"/g" \
              -e "s/value: \"false\"/value: \"true\"/g" \
              -e "s/requests:/# Reduced resources for dev\n        requests:/g" \
              -e "s/memory: \"256Mi\"/memory: \"128Mi\"/g" \
              -e "s/cpu: \"200m\"/cpu: \"100m\"/g" \
              -e "s/limits:/limits:/g" \
              -e "s/memory: \"512Mi\"/memory: \"256Mi\"/g" \
              -e "s/cpu: \"500m\"/cpu: \"300m\"/g" \
              k8s/deployment.yaml > k8s/dev/deployment.yaml
          
          # Copy and modify service for dev environment
          sed "s/namespace: devpocket-prod/namespace: ${{ env.KUBERNETES_NAMESPACE }}/g" \
              k8s/service.yaml > k8s/dev/service.yaml
          
          # Copy and modify ingress for dev environment
          sed -e "s/namespace: devpocket-prod/namespace: ${{ env.KUBERNETES_NAMESPACE }}/g" \
              -e "s/api.devpocket.app/${{ env.DOMAIN }}/g" \
              -e "s/devpocket-nodejs.prod.diginext.site/devpocket-nodejs.dev.diginext.site/g" \
              -e "s/tls-api-devpocket-app/tls-api-dev-devpocket-app/g" \
              -e "s/tls-devpocket-nodejs-prod-diginext-site/tls-devpocket-nodejs-dev-diginext-site/g" \
              k8s/ingress.yaml > k8s/dev/ingress.yaml
          
          # Copy namespace manifest
          sed "s/name: devpocket-prod/name: ${{ env.KUBERNETES_NAMESPACE }}/g" \
              k8s/namespace.yaml > k8s/dev/namespace.yaml
        env:
          BRANCH_SAFE: ${{ env.BRANCH_SAFE }}
          SHORT_SHA: ${{ env.SHORT_SHA }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/dev/namespace.yaml
          kubectl apply -f k8s/dev/service.yaml
          kubectl apply -f k8s/dev/deployment.yaml
          kubectl apply -f k8s/dev/ingress.yaml

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/devpocket-nodejs -n ${{ env.KUBERNETES_NAMESPACE }} --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -n ${{ env.KUBERNETES_NAMESPACE }} -l app.kubernetes.io/name=devpocket-nodejs
          kubectl get services -n ${{ env.KUBERNETES_NAMESPACE }} devpocket-nodejs
          kubectl get ingress -n ${{ env.KUBERNETES_NAMESPACE }} devpocket-nodejs

      - name: Run smoke tests
        run: |
          # Wait for ingress to be ready
          sleep 60
          
          # Test the API health endpoint
          if curl -f https://${{ env.DOMAIN }}/api/v1/health; then
            echo "✅ Health check passed"
          else
            echo "⚠️ Health check failed - this is expected for new dev deployments"
            kubectl logs -n ${{ env.KUBERNETES_NAMESPACE }} -l app.kubernetes.io/name=devpocket-nodejs --tail=20
          fi

  notify:
    runs-on: ubuntu-latest
    name: Notify Deployment Status
    needs: [test, build-and-push, deploy]
    if: always()
    
    steps:
      - name: Deployment Success
        if: needs.deploy.result == 'success'
        run: |
          echo "🚀 Development deployment successful!"
          echo "✅ Tests: ${{ needs.test.result }}"
          echo "✅ Build: ${{ needs.build-and-push.result }}"  
          echo "✅ Deploy: ${{ needs.deploy.result }}"
          echo "🌐 URL: https://${{ env.DOMAIN }}"
          echo "🏷️ Build: ${{ needs.build-and-push.outputs.build-number }}"

      - name: Deployment Failed
        if: needs.deploy.result == 'failure'
        run: |
          echo "❌ Development deployment failed!"
          echo "Tests: ${{ needs.test.result }}"
          echo "Build: ${{ needs.build-and-push.result }}"  
          echo "Deploy: ${{ needs.deploy.result }}"
          exit 1